name: Robot Framework Formulario Web 
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest

    steps:
    - name: checkout Repository 
      uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run:  |
        pip install robotframework
        pip install robotframework-faker
        pip install --upgrade robotframework-seleniumlibrary
        python3 -m pip install robotframework
        python -m pip install robotframework
        pip install --upgrade robotframework
        pip3 install --upgrade robotframework
        pip install setuptools 
        
    - name: Run Robot Frameworks testes
      run:  |
        robot -d formulario Web/testes
    - name: Arquive Robot Framework results 
      if: ${{always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Formulario-robot
        path: ./formulario
